import os
import numpy as np
import pandas as pd
import torch
import dgl
from collections import defaultdict
from scipy.spatial import cKDTree

class RVEProcessor:
    def __init__(self, node_path, elem_path, matrix_path, material_props):
        """
        node_path, elem_path, matrix_path:
          File paths generated by ../Pre_mesh2graph/mesh_data_extractor.py
        material_props: {'E1':.., 'nu1':.., 'E2':.., 'nu2':..} (1=Matrix, 2=Inclusion)
        """
        self.node_path = node_path
        self.elem_path = elem_path
        self.matrix_path = matrix_path
        self.props = material_props

        # Data containers
        self.nodes = {}
        self.elements = {}
        self.phase_labels = {}
        self.adjacency = defaultdict(set)
        self.pbc_adjacency = defaultdict(set)  # Store cross-boundary connections
        self.shared_faces = {}
        self.pbc_edge_info = {}  # Format: {(u, v): {'normal':.., 'dist':..}}

        # Geometric information
        self.box_size = None  # [Lx, Ly, Lz]
        self.mins = None

        # Loading and initialization
        self._load_mesh()
        self._build_adjacency()
        self._build_pbc()  # Calculates box_size and establishes micro PBCs

        # Mesoscopic data
        self.inclusions = {}
        self.element_to_inclusion = {}
        self.inclusion_adjacency = defaultdict(set)
        self._extract_inclusions()

    # ==========================
    # 0. Auxiliary Tools
    # ==========================
    def _get_derived_props(self, E, nu):
        """Derive physical properties: [E, nu, G, K]"""
        nu_safe = min(nu, 0.499)
        G = E / (2 * (1 + nu_safe))
        K = E / (3 * (1 - 2 * nu_safe))
        return np.array([E, nu, G, K], dtype=np.float32)

    def _get_centroid(self, verts):
        return np.mean([self.nodes[v] for v in verts], axis=0)

    def _calculate_vol(self, verts):
        v0, v1, v2, v3 = [self.nodes[v] for v in verts]
        return abs(np.linalg.det(np.column_stack([v1 - v0, v2 - v0, v3 - v0]))) / 6.0

    def _calculate_area(self, v0, v1, v2):
        p0, p1, p2 = self.nodes[v0], self.nodes[v1], self.nodes[v2]
        return np.linalg.norm(np.cross(p1 - p0, p2 - p0)) / 2.0

    def _spherical_sort(self, verts, centroid):
        rel = [self.nodes[v] - centroid for v in verts]
        sph = [(np.linalg.norm(c), np.arctan2(np.linalg.norm(c[:2]), c[2]), np.arctan2(c[1], c[0])) for c in rel]
        idx = np.lexsort(([p[2] for p in sph], [p[1] for p in sph]))
        return [verts[i] for i in idx]

    # ==========================
    # 1. Basic Loading and Geometric Construction
    # ==========================
    def _load_mesh(self):
        # Load Nodes
        with open(self.node_path, 'r') as f:
            f.readline()
            for line in f:
                parts = line.strip().split(',')
                if len(parts) >= 4:
                    self.nodes[int(parts[0])] = np.array([float(x) for x in parts[1:4]], dtype=np.float32)
        # Load Elements
        with open(self.elem_path, 'r') as f:
            f.readline()
            for line in f:
                parts = list(map(int, line.strip().replace(',', ' ').split()))
                if len(parts) >= 5:
                    self.elements[parts[0]] = parts[1:5]
        # Load Matrix Phase
        with open(self.matrix_path, 'r') as f:
            mat_set = set(map(int, f.read().split()))
        self.phase_labels = {eid: (0 if eid in mat_set else 1) for eid in self.elements}

    def _build_adjacency(self):
        face_dict = defaultdict(list)
        for eid, verts in self.elements.items():
            faces = [tuple(sorted([verts[i], verts[j], verts[k]]))
                     for i, j, k in [(0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3)]]
            for face in faces:
                face_dict[face].append(eid)
        for face, elems in face_dict.items():
            if len(elems) > 1:
                # Internal adjacency
                for i in range(len(elems)):
                    for j in range(i + 1, len(elems)):
                        u, v = elems[i], elems[j]
                        self.adjacency[u].add(v)
                        self.adjacency[v].add(u)
                        self.shared_faces[tuple(sorted((u, v)))] = face

    def _build_pbc(self):
        coords = np.array(list(self.nodes.values()))
        self.mins, maxs = np.min(coords, axis=0), np.max(coords, axis=0)

        # 🔥 Calculate and save Box Size
        self.box_size = maxs - self.mins
        self.box_size[self.box_size < 1e-6] = 1.0  # Safety fallback

        # Identify boundary faces
        face_to_elem = defaultdict(list)
        for eid, verts in self.elements.items():
            faces = [tuple(sorted([verts[i], verts[j], verts[k]]))
                     for i, j, k in [(0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3)]]
            for face in faces:
                face_to_elem[face].append(eid)

        boundary_faces = []
        for face, eids in face_to_elem.items():
            if len(eids) == 1:  # Faces attached to only one element are boundaries
                fc = np.mean([self.nodes[n] for n in face], axis=0)
                for ax in range(3):
                    if abs(fc[ax] - self.mins[ax]) < 1e-4:
                        boundary_faces.append((ax, -1, eids[0], face))  # -1: Left/Bottom/Back
                    elif abs(fc[ax] - maxs[ax]) < 1e-4:
                        boundary_faces.append((ax, 1, eids[0], face))  # 1: Right/Top/Front

        # KDTree matching for periodic boundaries
        neg_dict, pos_dict = defaultdict(list), defaultdict(list)
        for item in boundary_faces:
            if item[1] == -1:
                neg_dict[item[0]].append(item)
            else:
                pos_dict[item[0]].append(item)

        for ax in range(3):
            negs, poss = neg_dict[ax], pos_dict[ax]
            if not negs or not poss: continue

            # Project points from Pos faces back to near Neg faces for matching
            pos_centers = np.array([np.mean([self.nodes[n] for n in p[3]], axis=0) for p in poss])
            neg_centers_shifted = np.array([np.mean([self.nodes[n] for n in p[3]], axis=0) for p in negs])
            neg_centers_shifted[:, ax] += self.box_size[ax]  # Shift Neg to Pos

            tree = cKDTree(pos_centers)
            dists, idxs = tree.query(neg_centers_shifted)

            for i, idx in enumerate(idxs):
                if dists[i] < 1e-4:
                    u_info, v_info = negs[i], poss[idx]
                    u, v = u_info[2], v_info[2]  # Element IDs

                    self.pbc_adjacency[u].add(v)
                    self.pbc_adjacency[v].add(u)

                    # Record geometric features of PBC edges
                    face_nodes = u_info[3]
                    area = self._calculate_area(*face_nodes)
                    normal = np.zeros(3)
                    normal[ax] = -1.0  # Normalized direction

                    # True physical distance (across boundaries)
                    u_c = self._get_centroid(self.elements[u])
                    v_c = self._get_centroid(self.elements[v])

                    # Correct v's coordinates for distance calculation
                    v_c_virtual = v_c.copy()
                    v_c_virtual[ax] -= self.box_size[ax]
                    dist = np.linalg.norm(u_c - v_c_virtual)

                    self.pbc_edge_info[(u, v)] = {'area': area, 'normal': normal, 'dist': dist}
                    self.pbc_edge_info[(v, u)] = {'area': area, 'normal': -normal, 'dist': dist}

    # ==========================
    # 2. Mesoscopic Extraction (Inclusions)
    # ==========================
    def _extract_inclusions(self):
        visited = set()
        inc_id = 0
        inc_elems = [e for e, p in self.phase_labels.items() if p == 1]

        # Traverse only within Inclusions
        sub_adj = defaultdict(list)
        for e in inc_elems:
            for nei in self.adjacency[e]:  # Do not merge across PBC (assumes inclusions aren't cut)
                if self.phase_labels[nei] == 1:
                    sub_adj[e].append(nei)

        for seed in inc_elems:
            if seed in visited: continue
            cluster = []
            q = [seed]
            visited.add(seed)
            while q:
                cur = q.pop(0)
                cluster.append(cur)
                for nei in sub_adj[cur]:
                    if nei not in visited:
                        visited.add(nei)
                        q.append(nei)

            self._create_inclusion_props(inc_id, cluster)
            inc_id += 1

        # Build fully connected mesoscopic graph
        inc_ids = list(self.inclusions.keys())
        for i in range(len(inc_ids)):
            for j in range(i + 1, len(inc_ids)):
                u, v = inc_ids[i], inc_ids[j]
                self.inclusion_adjacency[u].add(v)
                self.inclusion_adjacency[v].add(u)

    def _create_inclusion_props(self, inc_id, elems):
        all_verts = set()
        for e in elems:
            all_verts.update(self.elements[e])
            self.element_to_inclusion[e] = inc_id

        pts = np.array([self.nodes[n] for n in all_verts])
        center = np.mean(pts, axis=0)

        # PCA for Shape Analysis
        centered_pts = pts - center
        cov = np.cov(centered_pts.T)
        evals, evecs = np.linalg.eigh(cov)
        idx = np.argsort(evals)[::-1]
        evals = evals[idx]
        evecs = evecs[:, idx]

        vol = sum([self._calculate_vol(self.elements[e]) for e in elems])
        self.inclusions[inc_id] = {'center': center, 'vol': vol, 'evals': evals, 'evecs': evecs}

    # ==========================
    # 3. Build Graphs (DGL)
    # ==========================
    def build_micro_graph(self):
        eids = sorted(self.elements.keys())
        eid_map = {e: i for i, e in enumerate(eids)}
        N = len(eids)

        # 1. Node Features
        feats = []
        for eid in eids:
            verts = self.elements[eid]
            cent = self._get_centroid(verts)
            sorted_v = self._spherical_sort(verts, cent)
            v_coords = np.concatenate([self.nodes[v] for v in sorted_v])
            phase = self.phase_labels[eid]
            p_vals = self._get_derived_props(self.props['E1'], self.props['nu1']) if phase == 0 \
                else self._get_derived_props(self.props['E2'], self.props['nu2'])
            vol = self._calculate_vol(verts)
            feats.append(np.hstack([cent, v_coords, [vol], p_vals]))

        g = dgl.graph(([], []), num_nodes=N)
        g.ndata['feat'] = torch.tensor(np.stack(feats), dtype=torch.float32)

        # Attribution index and meso_id
        inclusion_ids = np.full(N, -1, dtype=np.int32)
        for eid, inc_id in self.element_to_inclusion.items():
            if eid in eid_map:
                inclusion_ids[eid_map[eid]] = inc_id
        g.ndata['meso_id'] = torch.tensor(inclusion_ids, dtype=torch.long)

        # 2. Edge Features
        src_list, dst_list, edge_feats = [], [], []
        props_arr = g.ndata['feat'][:, -4:].numpy()
        feat_arr = g.ndata['feat'][:, :3].numpy()

        for eid_u in eids:
            u = eid_map[eid_u]
            phase_u = self.phase_labels[eid_u]  # Get source node phase

            # --- 1. Inner Edges ---
            for eid_v in self.adjacency[eid_u]:
                if eid_v in eid_map:
                    v = eid_map[eid_v]
                    phase_v = self.phase_labels[eid_v]  # Get target node phase

                    src_list.append(u)
                    dst_list.append(v)

                    # Basic geometric calculations
                    c_u, c_v = feat_arr[u], feat_arr[v]
                    diff = c_v - c_u
                    dist = np.linalg.norm(diff)
                    direction = diff / (dist + 1e-12)
                    ratios = props_arr[v] / (props_arr[u] + 1e-8)

                    # Normal vector processing
                    key = tuple(sorted((eid_u, eid_v)))
                    face = self.shared_faces.get(key)
                    area = self._calculate_area(*face) if face else 0.0
                    normal = direction  # Default direction
                    if face:
                        p0, p1, p2 = [self.nodes[n] for n in face]
                        n_raw = np.cross(p1 - p0, p2 - p0)
                        n_raw /= (np.linalg.norm(n_raw) + 1e-12)
                        normal = n_raw if np.dot(n_raw, direction) >= 0 else -n_raw

                    # 🔥 Modification: Use 2D phase labels [phase_u, phase_v]
                    topo_indicator = np.array([phase_u, phase_v], dtype=np.float32)

                    # Concatenate 14D features: [3(dir), 1(dist), 3(norm), 1(area), 4(ratios), 2(topo)]
                    edge_feats.append(np.hstack([direction, [dist], normal, [area], ratios, topo_indicator]))

            # --- 2. Periodic Boundary (PBC) Edges ---
            for eid_v in self.pbc_adjacency[eid_u]:
                if eid_v in eid_map:
                    v = eid_map[eid_v]
                    phase_v = self.phase_labels[eid_v]  # Get target node phase

                    src_list.append(u)
                    dst_list.append(v)

                    info = self.pbc_edge_info.get((eid_u, eid_v))
                    ratios = props_arr[v] / (props_arr[u] + 1e-8)

                    # 🔥 Modification: Use 2D phase labels for PBC edges as well
                    topo_indicator = np.array([phase_u, phase_v], dtype=np.float32)

                    edge_feats.append(np.hstack([
                        info['normal'], [info['dist']], info['normal'],
                        [info['area']], ratios, topo_indicator
                    ]))

        g.add_edges(src_list, dst_list)
        g.edata['feat'] = torch.tensor(np.stack(edge_feats), dtype=torch.float32)
        return g

    def build_meso_graph(self):
        """Build Meso Graph: Inclusions + Matrix Props + PBC Convention"""
        inc_ids = sorted(self.inclusions.keys())
        N = len(inc_ids)

        if N == 0:
            g = dgl.graph(([], []), num_nodes=1)
            # Dimensions must match the feats below
            g.ndata['feat'] = torch.zeros((1, 20))
            return g

        idx_map = {inc: i for i, inc in enumerate(inc_ids)}

        # Property preparation
        inc_props = self._get_derived_props(self.props['E2'], self.props['nu2'])  # Node feat
        mat_props = self._get_derived_props(self.props['E1'], self.props['nu1'])  # Edge feat

        # 1. Node Features
        feats = []
        for inc in inc_ids:
            info = self.inclusions[inc]
            # [Center(3) + Geo(13) + Props(4)] = 20
            # 🔥 Key Modification: Added Center to support 3D visualization
            f = np.hstack([info['center'], info['evals'], info['evecs'].flatten(), [info['vol']], inc_props])
            feats.append(f)

        g = dgl.graph(([], []), num_nodes=N)
        g.ndata['feat'] = torch.tensor(np.stack(feats), dtype=torch.float32)

        # 2. Edge Features (with PBC)
        src, dst, e_feats = [], [], []

        for inc_u in inc_ids:
            u = idx_map[inc_u]
            info_u = self.inclusions[inc_u]

            for inc_v in self.inclusion_adjacency[inc_u]:
                if inc_v in idx_map:
                    v = idx_map[inc_v]
                    info_v = self.inclusions[inc_v]

                    src.append(u)
                    dst.append(v)

                    # Raw vector
                    raw_diff = info_v['center'] - info_u['center']

                    # 🔥 Minimum Image Convention (PBC correction) 🔥
                    # dx = dx - L * round(dx / L)
                    pbc_diff = raw_diff - self.box_size * np.round(raw_diff / self.box_size)

                    dist = np.linalg.norm(pbc_diff)
                    direction = pbc_diff / (dist + 1e-12)

                    # [Dir(3), Dist(1), MatProps(4)] = 8
                    ef = np.hstack([direction, [dist], mat_props])
                    e_feats.append(ef)

        if src:
            g.add_edges(src, dst)
            g.edata['feat'] = torch.tensor(np.stack(e_feats), dtype=torch.float32)

        return g


# ==========================================
# 4. Dataset Generation and Saving Logic
# ==========================================
def process_dataset(csv_path, data_root, save_dir, sample_indices=None):
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    df = pd.read_csv(csv_path)
    # Save original indices
    df['folder_id'] = df.index

    if sample_indices is not None:
        df = df.iloc[sample_indices].reset_index(drop=True)

    # Target columns (Last 12)
    target_cols = ['E11', 'E22', 'E33', 'G23', 'G13', 'G12',
                   'v12', 'v13', 'v21', 'v23', 'v31', 'v32']

    print(f"Starting processing of {len(df)} samples...")

    for idx in range(len(df)):
        row = df.iloc[idx]
        real_id = int(row['folder_id'])

        # --- 🔥 Skip existing files to save computation time 🔥 ---
        save_path = os.path.join(save_dir, f"sample_{real_id}.bin")
        if os.path.exists(save_path):
            print(f"[Skipping] Sample {real_id} already exists at {save_path}")
            continue

        # Find target folder
        possible_dirs = [
            os.path.join(data_root, f"particle_3d_{real_id + 1}_mesh"),  # Prioritize your filename pattern
            os.path.join(data_root, f"ellipsoids_3d_{real_id + 1}_mesh"),
            os.path.join(data_root, f"sample_{real_id}"),
            os.path.join(data_root, f"WT-EH{real_id + 1}_mesh"),
            os.path.join(data_root, f"WT-F{real_id + 1}_mesh"),
            os.path.join(data_root, f"copped_fiber_3d_{real_id + 1}_mesh"),
            os.path.join(data_root, f"UnitCell{real_id + 1}_mesh"),
            os.path.join(data_root, f"25UQ25-{real_id + 1}_mesh"),
        ]
        sample_dir = next((d for d in possible_dirs if os.path.exists(d)), None)

        if not sample_dir:
            print(f"[Warning] Skipping ID {real_id}: Directory not found in {data_root}")
            continue

        print(f"Processing Sample {real_id}...")

        # Extract material properties
        mat_props = {
            'E1': row['E_1'], 'nu1': row['V1'],
            'E2': row['E2'], 'nu2': row['V2']
        }

        # Extract Label
        label = torch.tensor(row[target_cols].values.astype(np.float32))

        try:
            processor = RVEProcessor(
                os.path.join(sample_dir, "node.txt"),
                os.path.join(sample_dir, "element.txt"),
                os.path.join(sample_dir, "matrix.txt"),
                mat_props
            )

            g_micro = processor.build_micro_graph()
            g_meso = processor.build_meso_graph()

            # Save
            save_path = os.path.join(save_dir, f"sample_{real_id}.bin")
            # dgl.save_graphs can save graph lists and label dictionaries
            dgl.save_graphs(save_path, [g_micro, g_meso], {'label': label.unsqueeze(0)})

        except Exception as e:
            print(f"Error processing sample {real_id}: {e}")
            import traceback
            traceback.print_exc()


# ==========================================
# 5. Testing and Verification
# ==========================================
if __name__ == "__main__":
    # Configuration paths
    CSV_PATH = "../example_data/copped_fiber/csv/CF.csv"
    DATA_ROOT = "../example_data/copped_fiber/extracted/"
    SAVE_DIR = "..//example_data/copped_fiber//BIN/"  # Output directory

    # 1. Run test on a single sample (Sample 0)
    print("=== Running Test on Sample 0 ===")
    process_dataset(CSV_PATH, DATA_ROOT, SAVE_DIR, sample_indices=None)

    # 2. Read and verify
    bin_path = os.path.join(SAVE_DIR, "sample_0.bin")
    if os.path.exists(bin_path):
        gs, label_dict = dgl.load_graphs(bin_path)
        g_micro = gs[0]
        g_meso = gs[1]
        label = label_dict['label']

        print("\n" + "=" * 50)
        print("      VERIFICATION REPORT")
        print("=" * 50)

        print(f"Files saved at: {os.path.abspath(SAVE_DIR)}")
        print(f"Loaded graphs: {len(gs)} (Expected 2: [0]=Micro, [1]=Meso)")
        print(f"Label shape: {label.shape}")

        print("\n[Micro Graph]")
        print(f"  Nodes: {g_micro.num_nodes()}")
        print(f"  Edges: {g_micro.num_edges()}")
        # 🔥 Update expected dimensions
        print(f"  Node Feature Dim: {g_micro.ndata['feat'].shape[1]} (Expected 20)")
        print(f"  Edge Feature Dim: {g_micro.edata['feat'].shape[1]} (Expected 14: Geo(8)+Props(4)+Topo(2))")

        # Simple sampling check for 2D phase encoding
        if g_micro.num_edges() > 0:
            sample_edge_feat = g_micro.edata['feat'][0, -2:]
            print(f"  Sample Edge Topo Encoding: {sample_edge_feat.numpy()} (e.g., [0,1] for Matrix-to-Inclusion)")

        print("\n[Meso Graph]")
        print(f"  Nodes (Inclusions): {g_meso.num_nodes()}")
        # Should be 20 here (includes the Center at the first 3 indices)
        print(f"  Node Feature Dim: {g_meso.ndata['feat'].shape[1]} (Expected 20: Center(3)+Geo(13)+Props(4))")
        print(f"  Edge Feature Dim: {g_meso.edata['feat'].shape[1] if g_meso.num_edges() > 0 else 'N/A'}")

        print("\nAll checks passed. Ready for batch processing.")